services:
  cyber-resilience-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      # SMTP Configuration
      SMTP_HOST: smtp.protonmail.ch # Example: smtp.gmail.com, smtp.sendgrid.net
      SMTP_PORT: 587 # 587 for TLS, 465 for SSL, 25 for unencrypted
      FROM_EMAIL: no-reply@stwlfrm.monster # The email address that appears in "From"

      # Optional: Port configuration
      PORT: 3000
    volumes:
      # Mount PDF output directory to persist generated PDFs
      - ./pdf_output:/app/pdf_output
    restart: unless-stopped
