services:
  cyber-resilience-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      # SMTP Configuration
      SMTP_HOST: smtp.mailersend.net # Example: smtp.gmail.com, smtp.sendgrid.net
      SMTP_PORT: 587 # 587 for TLS, 465 for SSL, 25 for unencrypted
      SMTP_USER: MS_F2pHKB@stwlfrm.monster # Your SMTP username
      SMTP_PASS: mssp.hwizh9I.k68zxl237q5gj905.4hAhhAe # Your SMTP password or app password
      FROM_EMAIL: cwhite@stwlfrm.monster # The email address that appears in "From"

      # Optional: Port configuration
      PORT: 3000
    volumes:
      # Mount PDF output directory to persist generated PDFs
      - ./pdf_output:/app/pdf_output
    restart: unless-stopped
