version: "3.8"

services:
  cyber-resilience-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      # SMTP Configuration
      SMTP_HOST: smtp.mailersend.net # Example: smtp.gmail.com, smtp.sendgrid.net
      SMTP_PORT: 587 # 587 for TLS, 465 for SSL, 25 for unencrypted
      SMTP_USER: SMTP_USER=MS_43tG37@test-r9084zvddp8gw63d.mlsender.net # Your SMTP username
      SMTP_PASS: mssp.gv9izTL.yzkq3403ep24d796.RNEmMBQ # Your SMTP password or app password
      FROM_EMAIL: cwhite@stwlfrm.monster # The email address that appears in "From"

      # Optional: Port configuration
      PORT: 3000
    volumes:
      # Mount PDF output directory to persist generated PDFs
      - ./pdf_output:/app/pdf_output
    restart: unless-stopped
